packageExtensions:
  cascading-color-systems@*:
    peerDependencies:
      core-js: '>=3'
  eslint-module-utils@*:
    peerDependencies:
      eslint: '*'
  eslint-plugin-prettier@*:
    peerDependencies:
      eslint-config-prettier: '*'
  sassdoc@*:
    peerDependencies:
      sassdoc-theme-herman: '*'
  stylelint-prettier@*:
    peerDependencies:
      stylelint-config-prettier: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-2.2.2.cjs
